name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm install tfx-cli
    - run: npm-do tfx extension create --manifest-globs vss-extension.json
